/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'aboutMe' : IDL.Text,
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const MailContent = IDL.Variant({
  'notification' : IDL.Text,
  'joinRequest' : IDL.Record({
    'requester' : IDL.Principal,
    'message' : IDL.Text,
    'teamId' : IDL.Nat,
  }),
});
export const MailType = IDL.Variant({
  'notification' : IDL.Null,
  'joinRequest' : IDL.Null,
});
export const Mail = IDL.Record({
  'id' : IDL.Nat,
  'content' : MailContent,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'mailType' : MailType,
});
export const PDFDocument = IDL.Record({
  'content' : IDL.Vec(IDL.Nat8),
  'filename' : IDL.Text,
});
export const Image = IDL.Record({
  'contentType' : IDL.Text,
  'filename' : IDL.Text,
  'bytes' : IDL.Vec(IDL.Nat8),
});
export const TeamDTO = IDL.Record({
  'id' : IDL.Nat,
  'files' : IDL.Vec(PDFDocument),
  'members' : IDL.Vec(IDL.Principal),
  'joinRequests' : IDL.Vec(IDL.Principal),
  'icon' : IDL.Opt(Image),
  'name' : IDL.Text,
  'leader' : IDL.Principal,
  'videos' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveJoinRequests' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTeam' : IDL.Func([IDL.Text, IDL.Vec(IDL.Principal)], [IDL.Nat], []),
  'deleteMailItem' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamFootage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'denyJoinRequests' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
  'disbandTeam' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(Mail)], ['query']),
  'getTeam' : IDL.Func([IDL.Nat], [TeamDTO], ['query']),
  'getTeamFootage' : IDL.Func([IDL.Nat], [IDL.Vec(ExternalBlob)], ['query']),
  'getTeamMembershipStatus' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveTeam' : IDL.Func([], [], []),
  'listTeams' : IDL.Func([], [IDL.Vec(TeamDTO)], ['query']),
  'markMailItemAsRead' : IDL.Func([IDL.Nat], [], []),
  'removeMemberFromTeam' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'requestJoinTeam' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadFile' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'uploadTeamFootage' : IDL.Func([IDL.Nat, IDL.Text, ExternalBlob], [], []),
  'uploadTeamIcon' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'aboutMe' : IDL.Text,
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const MailContent = IDL.Variant({
    'notification' : IDL.Text,
    'joinRequest' : IDL.Record({
      'requester' : IDL.Principal,
      'message' : IDL.Text,
      'teamId' : IDL.Nat,
    }),
  });
  const MailType = IDL.Variant({
    'notification' : IDL.Null,
    'joinRequest' : IDL.Null,
  });
  const Mail = IDL.Record({
    'id' : IDL.Nat,
    'content' : MailContent,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'mailType' : MailType,
  });
  const PDFDocument = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
  });
  const Image = IDL.Record({
    'contentType' : IDL.Text,
    'filename' : IDL.Text,
    'bytes' : IDL.Vec(IDL.Nat8),
  });
  const TeamDTO = IDL.Record({
    'id' : IDL.Nat,
    'files' : IDL.Vec(PDFDocument),
    'members' : IDL.Vec(IDL.Principal),
    'joinRequests' : IDL.Vec(IDL.Principal),
    'icon' : IDL.Opt(Image),
    'name' : IDL.Text,
    'leader' : IDL.Principal,
    'videos' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveJoinRequests' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTeam' : IDL.Func([IDL.Text, IDL.Vec(IDL.Principal)], [IDL.Nat], []),
    'deleteMailItem' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamFootage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'denyJoinRequests' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
    'disbandTeam' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInbox' : IDL.Func([], [IDL.Vec(Mail)], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [TeamDTO], ['query']),
    'getTeamFootage' : IDL.Func([IDL.Nat], [IDL.Vec(ExternalBlob)], ['query']),
    'getTeamMembershipStatus' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveTeam' : IDL.Func([], [], []),
    'listTeams' : IDL.Func([], [IDL.Vec(TeamDTO)], ['query']),
    'markMailItemAsRead' : IDL.Func([IDL.Nat], [], []),
    'removeMemberFromTeam' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'requestJoinTeam' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadFile' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'uploadTeamFootage' : IDL.Func([IDL.Nat, IDL.Text, ExternalBlob], [], []),
    'uploadTeamIcon' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };