/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Image {
  'contentType' : string,
  'filename' : string,
  'bytes' : Uint8Array,
}
export interface Mail {
  'id' : bigint,
  'content' : MailContent,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'mailType' : MailType,
}
export type MailContent = { 'notification' : string } |
  {
    'joinRequest' : {
      'requester' : Principal,
      'message' : string,
      'teamId' : bigint,
    }
  };
export type MailType = { 'notification' : null } |
  { 'joinRequest' : null };
export interface PDFDocument { 'content' : Uint8Array, 'filename' : string }
export interface TeamDTO {
  'id' : bigint,
  'files' : Array<PDFDocument>,
  'members' : Array<Principal>,
  'joinRequests' : Array<Principal>,
  'icon' : [] | [Image],
  'name' : string,
  'leader' : Principal,
  'videos' : Array<ExternalBlob>,
}
export interface UserProfile {
  'aboutMe' : string,
  'name' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveJoinRequests' : ActorMethod<[bigint, Array<Principal>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTeam' : ActorMethod<[string, Array<Principal>], bigint>,
  'deleteMailItem' : ActorMethod<[bigint], undefined>,
  'deleteTeamFootage' : ActorMethod<[bigint, string], undefined>,
  'denyJoinRequests' : ActorMethod<[bigint, Array<Principal>], undefined>,
  'disbandTeam' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInbox' : ActorMethod<[], Array<Mail>>,
  'getTeam' : ActorMethod<[bigint], TeamDTO>,
  'getTeamFootage' : ActorMethod<[bigint], Array<ExternalBlob>>,
  'getTeamMembershipStatus' : ActorMethod<[], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'leaveTeam' : ActorMethod<[], undefined>,
  'listTeams' : ActorMethod<[], Array<TeamDTO>>,
  'markMailItemAsRead' : ActorMethod<[bigint], undefined>,
  'removeMemberFromTeam' : ActorMethod<[bigint, Principal], undefined>,
  'requestJoinTeam' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadFile' : ActorMethod<[bigint, string, Uint8Array], undefined>,
  'uploadTeamFootage' : ActorMethod<[bigint, string, ExternalBlob], undefined>,
  'uploadTeamIcon' : ActorMethod<
    [bigint, string, string, Uint8Array],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];